/**
 * Contains pre-written React code snippet examples demonstrating usage.
 * @constant {Object<string, string>}
 */
export const CODE_EXAMPLES = {
  tsUsage: [
    "import LoaderOverlay, { LoaderOverlayProps }",
    "  from 'loader-overlay';",
    "",
    "const props: LoaderOverlayProps = {",
    "  show: true,",
    "  type: 'spinner',",
    "  variant: 'dark',",
    "};",
  ].join("\n"),

  minimal: [
    "import { useState } from 'react';",
    "import LoaderOverlay from 'loader-overlay';",
    "",
    "export default function App() {",
    "  const [loading, setLoading] = useState(false);",
    "",
    "  const fetchData = async () => {",
    "    setLoading(true);",
    "    await fetch('/api/data');",
    "    setLoading(false);",
    "  };",
    "",
    "  return (",
    "    <div style={{ position: 'relative' }}>",
    "      <LoaderOverlay show={loading} />",
    "      <button onClick={fetchData}>Load Data</button>",
    "    </div>",
    "  );",
    "}",
  ].join("\n"),

  withProgress: [
    "import { useState } from 'react';",
    "import LoaderOverlay from 'loader-overlay';",
    "",
    "export default function UploadPage() {",
    "  const [loading, setLoading] = useState(false);",
    "  const [progress, setProgress] = useState(0);",
    "",
    "  const upload = async () => {",
    "    setLoading(true);",
    "    for (let i = 0; i <= 100; i += 10) {",
    "      setProgress(i);",
    "      await new Promise(r => setTimeout(r, 300));",
    "    }",
    "    setLoading(false);",
    "  };",
    "",
    "  return (",
    "    <div style={{ position: 'relative' }}>",
    "      <LoaderOverlay",
    "        show={loading}",
    "        showProgress",
    "        progress={progress}",
    '        message="Uploading file..."',
    '        variant="gradient"',
    '        color="#60d394"',
    "      />",
    "      <button onClick={upload}>Upload</button>",
    "    </div>",
    "  );",
    "}",
  ].join("\n"),

  outsideClick: [
    "<LoaderOverlay",
    "  show={isLoading}",
    "  fullScreen",
    '  type="dots"',
    '  variant="blur"',
    '  message="Processing..."',
    "  closable",
    "  closeOnOutsideClick",
    "  onClose={() => setIsLoading(false)}",
    "/>",
  ].join("\n"),

  apiCall: [
    "import LoaderOverlay from 'loader-overlay';",
    "",
    "function UserProfile({ userId }) {",
    "  const [user, setUser] = useState(null);",
    "  const [loading, setLoading] = useState(true);",
    "",
    "  useEffect(() => {",
    "    fetch('/api/users/' + userId)",
    "      .then(r => r.json())",
    "      .then(data => { setUser(data); setLoading(false); });",
    "  }, [userId]);",
    "",
    "  return (",
    "    <div style={{ position: 'relative', minHeight: 200 }}>",
    "      <LoaderOverlay",
    "        show={loading}",
    "        fullScreen={false}",
    '        type="ring"',
    '        message="Loading profile..."',
    '        variant="blur"',
    "        blur={12}",
    "      />",
    "      {user && <h1>{user.name}</h1>}",
    "    </div>",
    "  );",
    "}",
  ].join("\n"),

  routerTransition: [
    "// React Router v6 route transition loader",
    "import LoaderOverlay from 'loader-overlay';",
    "",
    "export default function RootLayout() {",
    "  const navigation = useNavigation();",
    "  const isNavigating = navigation.state !== 'idle';",
    "",
    "  return (",
    "    <>",
    "      <LoaderOverlay",
    "        show={isNavigating}",
    "        fullScreen",
    '        type="dots"',
    '        variant="dark"',
    '        message="Navigating..."',
    "        zIndex={9999}",
    "      />",
    "      <Outlet />",
    "    </>",
    "  );",
    "}",
  ].join("\n"),

  customChildren: [
    '<LoaderOverlay show={loading} variant="dark">',
    "  <div style={{ textAlign: 'center' }}>",
    '    <img src="/logo-animated.svg" width={64} alt="loading" />',
    "    <p style={{ color: 'white', margin: '12px 0 0' }}>",
    "      Brewing your dashboard ☕",
    "    </p>",
    "  </div>",
    "</LoaderOverlay>",
  ].join("\n"),

  useLoaderHook: [
    "import { useState, useCallback } from 'react';",
    "import LoaderOverlay from 'loader-overlay';",
    "",
    "function useLoader() {",
    "  const [state, setState] = useState({",
    "    show: false, message: 'Loading...', progress: 0,",
    "  });",
    "  const start = useCallback((msg = 'Loading...') =>",
    "    setState({ show: true, message: msg, progress: 0 }), []);",
    "  const stop = useCallback(() =>",
    "    setState(s => ({ ...s, show: false })), []);",
    "  return { loaderProps: state, start, stop };",
    "}",
    "",
    "function MyPage() {",
    "  const { loaderProps, start, stop } = useLoader();",
    "  return (",
    "    <>",
    "      <LoaderOverlay {...loaderProps} showProgress fullScreen />",
    "      <button onClick={() => {",
    "        start('Saving...');",
    "        setTimeout(stop, 2000);",
    "      }}>Save</button>",
    "    </>",
    "  );",
    "}",
  ].join("\n"),
};

/**
 * The default configuration state for the interactive demo playground.
 * @constant {import('../types/demo.js').DemoConfiguration}
 */
export const DEFAULT_DEMO_CONFIG = {
  show: true,
  type: "spinner",
  size: "md",
  variant: "dark",
  color: "#a78bfa",
  message: "Loading...",
  submessage: "",
  fullScreen: false,
  zIndex: 10,
  opacity: 1,
  blur: 8,
  showProgress: false,
  progress: 0,
  closable: false,
  position: "center",
  animateIn: true,
  timeout: 0,
  closeOnOutsideClick: false,
};

/**
 * A set of JavaScript/React syntax keywords mapped to the 'kw' highlighting token.
 * @constant {Set<string>}
 */
export const SYNTAX_KEYWORDS = new Set([
  "import",
  "export",
  "from",
  "default",
  "function",
  "return",
  "const",
  "let",
  "var",
  "true",
  "false",
  "null",
  "undefined",
  "async",
  "await",
  "useEffect",
  "useState",
  "useRef",
  "useCallback",
  "if",
  "else",
  "for",
]);

/**
 * A mapping of code token types to their respective syntax highlighting colors.
 * @constant {Object<string, string>}
 */
export const SYNTAX_COLORS = {
  cm: "#6a9f6a",
  st: "#f4a261",
  kw: "#c084fc",
  tag: "#60d394",
  nm: "#81c8ff",
  op: "#888888",
  id: "#e2e8f0",
};

/**
 * An array representing the properties table documentation.
 * Each array entry contains [property_name, type, default, description].
 * @constant {string[][]}
 */
export const PROPS_DOCUMENTATION = [
  ["show", "boolean", "true", "Controls visibility"],
  ["type", "string", "'spinner'", "spinner | dots | pulse | bar | ring"],
  ["size", "string", "'md'", "sm | md | lg | xl"],
  [
    "variant",
    "string",
    "'dark'",
    "light | dark | blur | transparent | gradient",
  ],
  ["color", "string", "'#a78bfa'", "Accent color (hex/rgb/css var)"],
  ["message", "string", "'Loading...'", "Primary text below loader"],
  ["submessage", "string", "''", "Secondary/hint text"],
  ["fullScreen", "boolean", "true", "Cover viewport vs parent element"],
  ["lockScroll", "boolean", "true", "Lock body scroll when active"],
  ["zIndex", "number", "9999", "CSS z-index of overlay"],
  ["opacity", "number", "1", "Background opacity (0–1)"],
  ["blur", "number", "8", "Backdrop blur in px"],
  ["showProgress", "boolean", "false", "Show animated progress bar"],
  ["progress", "number", "0", "Progress value (0–100)"],
  ["closable", "boolean", "false", "Show ✕ close button"],
  ["onClose", "function", "()=>{}", "Callback when closed"],
  ["position", "string", "'center'", "center | top | bottom"],
  ["animateIn", "boolean", "true", "Fade-in animation on mount"],
  ["timeout", "number", "0", "Auto-hide after ms (0 = never)"],
  ["children", "node", "null", "Custom loader content override"],
  ["closeOnOutsideClick", "boolean", "false", "Close overlay on outside click"],
  ["onOutsideClick", "function", "()=>{}", "Callback fired on outside click"],
];
